pkg_name=effortless-guacd
pkg_origin=devioptimist
pkg_version="1.0.0"
pkg_maintainer="sbrown@chef.io"
pkg_license=("Apache-2.0")
pkg_scaffolding="chef/scaffolding-chef-infra"
pkg_deps=(core/dpkg core/make core/gcc)
scaffold_policy_name="Policyfile"
scaffold_policyfile_path="$PLAN_CONTEXT/../" # habitat/../Policyfile.rb
